version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fan-fam-serverless-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1095myft4zy2w"
s3_prefix = "fan-fam-serverless-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
